name = "4cwc-indonesia"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "4cwc-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
