/// <reference types="astro/client" />

// D1Database and the global `Env`/`Cloudflare.Env` types come from the file
// generated by `npx wrangler types` (worker-configuration.d.ts, gitignored —
// regenerate it after cloning or after editing wrangler.toml).

declare namespace App {
  interface Locals {
    user: import("./lib/db").SessionUser | null;
    lang: import("./lib/i18n").Lang;
    t: (key: string) => string;
  }
}
